### This step follows after user creation
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
    "username": "bob",
    "password": "password_at_least_7_characters"
}

###